-- Rename the STUDENTS.ST_ID to STUDENTS.STUDENT_ID
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

-- Change the length of STUDENTS.ST_NAME and STUDENTS.ST_LAST from 20 to 30
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(30);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(30);

-- Change the name of the INTERESTS.INTEREST to INTERESTS and its type to array of strings
ALTER TABLE INTERESTS RENAME COLUMN INTEREST TO INTERESTS;

-- Create a new table to store the aggregated interests
CREATE TABLE INTERESTS_MITIGATED AS
SELECT DISTINCT STUDENT_ID, ARRAY_AGG(INTERESTS) AS INTERESTS
FROM INTERESTS
GROUP BY STUDENT_ID
ORDER BY STUDENT_ID;

-- Delete the existing INTERESTS table
DROP TABLE INTERESTS;

-- Rename the new table to INTERESTS
ALTER TABLE INTERESTS_MITIGATED RENAME TO INTERESTS;

-- Display final tables
SELECT * FROM STUDENTS;
SELECT * FROM INTERESTS;